apiVersion: apps/v1
kind: Deployment
metadata:
  name: skilltrade-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skilltrade-payments
  template:
    metadata:
      labels:
        app: skilltrade-payments
    spec:
      containers:
        - name: skilltrade-payments
          image: whispernet/skilltrade-payments
          env:
            - name: NATS_CLUSTER_ID
              value: skilltrade
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: MONGO_URI
              value: "mongodb://skilltrade-payments-mongodb-srv:27017/skilltrade-payments"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: skilltrade-payments-srv
spec:
  selector:
    app: skilltrade-payments
  ports:
    - name: skilltrade-payments
      port: 3000
      targetPort: 3000
